### ISSUE TITLE
AWS Lambda support?

### ISSUE THREAD

**Issue by gavinengel** [devdazed/partition.io#3]
I'm curious, do you see this being used with AWS Lambda?

**Comment by devdazed** [comment]
I haven't looked into lambda too much, but this repo was largely an academic exercise on my part. I wouldn't recommend using it in a production capacity unless someone takes over maintenance o fit.

**Comment by gavinengel** [comment]
I don't really have project in mind.  It just caught my eye, and made me wonder about Lambda.  Thanks for your work.
